apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: koden-formation-mongodb
  namespace: argocd
spec:
  project: koden
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.6.5
    chart: mongodb
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/koden-process/formation-mongodb-k8s/refs/heads/main/values.yaml
      values: |
        auth:
          existingSecret: koden-formation-mongodb-secret
          usernames:
            - koden
          databases:
            - meow
  destination:
    server: https://kubernetes.default.svc
    namespace: koden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true